[project]
name = "akon-lang"  # Nombre del paquete en PyPI
version = "0.1.0"
description = "Akon Programming Language: El puente entre C y Python para Rob√≥tica y ML"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]